#!/bin/sh
#
# Copyright (c) 2013, "Steve Grubb <sgrubb@redhat.com>", Red Hat
# ALL RIGHTS RESERVED.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#    Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#    Neither the name of Red Hat nor the names of author(s) may be used to
# endorse or promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


if [ "$#" != "2" ] ; then
	echo "Usage: rpm-compare rpm1 rpm2"
	exit 1
fi

# Memorize our location so we can come back to it.
cwd=`pwd`
trap "cd $cwd; rm -rf rpm1 rpm2; rm -f list1 list2; exit 1" 1 2 3 5 15

# This cleanup should never be needed
if [ -e rpm1 ] ; then
	echo "Erasing rpm1 directory"
	rm -rf rpm1
fi
if [ -e rpm2 ] ; then
	echo "Erasing rpm2 directory"
	rm -rf rpm2
fi

# Make the working dirs
mkdir rpm1
mkdir rpm2

#Make sure nothing prevented making them
if [ ! -d rpm1 ] ; then
	echo "rpm1 dir does not exist"
	exit 1
fi
if [ ! -d rpm2 ] ; then
	echo "rpm2 dir does not exist"
	exit 1
fi

cd rpm1
if [ $? -ne 0 ] ; then
	echo "Could not cd into rpm1 dir"
	exit 1
fi

# Extract rpm1
rpm2cpio $1 | cpio -dim --no-absolute-filenames 2>/dev/null

cd $cwd/rpm2
if [ $? -ne 0 ] ; then
	echo "Could not cd into rpm2 dir"
	exit 1
fi

# Extract rpm2
rpm2cpio $2 | cpio -dim --no-absolute-filenames 2>/dev/null
cd $cwd
if [ $? -ne 0 ] ; then
	echo "Could not cd into $cwd"
	exit 1
fi

# Make a manifest list for quick compare. If the file lists are
# different we have very different rpms and can stop right here.
rpm -qpl $1 > list1
rpm -qpl $2 > list2
diff -u list1 list2 >/dev/null
if [ $? -ne 0 ] ; then
	echo "Difference found in package manifest:"
	diff -u list1 list2
	exit 1
fi

# If we hit a package with no files, we are done. We only check
# one because we already made sure manifests are the same.
f=`cat list1 | grep -v '(contains no files)'`
if [ x"$f" = "x" ] ; then
	echo "Packages are the same"
	rm -f list1 list2
	rm -rf rpm1 rpm2
	exit 0
fi

# Start the real analysis
cnt=0
for f in `cat list1`
do
	# Skip symlinks
	if [ -h $cwd/rpm1/$f ] || [ -h $cwd/rpm2/$f ] ; then
		continue
	fi
	test1=`echo $cwd/rpm1/$f | /usr/bin/file -f - 2>/dev/null | grep ELF`
	if [ x"$test1" != "x" ] ; then
		test2=`echo $cwd/rpm2/$f | /usr/bin/file -f - 2>/dev/null | grep ELF`
		if [ x"$test2" != "x" ] ; then
			# If we get to here, both are ELF format
			base=`basename $f`
			objdump -d rpm1/$f | grep -v $base > dump1
			objdump -d rpm2/$f | grep -v $base > dump2
			diff -u dump1 dump2 > /dev/null
			if [ $? -ne 0 ] ; then
				echo "File disassembly differs $f"
				cnt=`expr $cnt + 1`
			fi
			rm -f dump1 dump2
		else
			echo "File type differs $f"
			cnt=`expr $cnt + 1`
		fi
	elif [ -f rpm1/$f ] && [ -f rpm2/$f ] ; then
		# If here, not ELF. Do simple hash compare.
		h1=`sha256sum rpm1/$f | awk '{ print $1 }'`
		h2=`sha256sum rpm2/$f | awk '{ print $1 }'`
		if [ "$h1" != "$h2" ] ; then
			echo "File hash differs $f"
			cnt=`expr $cnt + 1`
		fi
	fi
done

# Done cleanup
rm -f list1 list2
rm -rf rpm1 rpm2

# Output the conclusion
if [ $cnt -ne 0 ] ; then
	echo "The packages differ"
	exit 1
fi
echo "The packages are the same"
exit 0

